
export const products = [
    {
      src: "/topyyii.jpg",
      alt: "top",
      title: "Red top",
      description: "A stylish red top, perfect for casual outings. Its vibrant color adds a bold statement to your wardrobe.",
      price: 125,
      Category: "Red-top",
      slug: "tops",
      id: "top1",
    },
    {
      src: "/topss1.jpg",
      alt: "tshirt",
      title: "Black top",
      description: "A classic black top that offers simplicity and versatility. Ideal for pairing with any outfit, it&apos;s a must-have for every season",
      price: 100,
      Category: "black-top",
      slug: "black-top",
      id: "blackTop",
    },
    {
      src: "/Top2.jpeg",
      alt: "top",
      title: "White Top",
      description: "Elevate your look with this elegant white top. Its minimalistic design makes it a great choice for both casual and semi-formal occasions.",
      price: 125,
      Category: "White Top",
      slug: "white-top",
      id: "whiteTop",
    },
    {
      src: "/top3.jpg",
      alt: "top",
      title: "Fancy Top",
      description: "This fancy top combines modern style with a touch of glam. Perfect for parties or special events, it&apos;s designed to make a statement.",
      price:220,
      Category: "top",
      slug: "fancy-top",
      id: "fancytop",
    },
    {
      src: "/Topss4.jpg",
      alt: "top",
      title: "Printed top",
      description: "A floral-printed top that exudes charm and vibrancy. Its playful design is great for summer outings and adds a cheerful vibe to your style.",
      price: 100,
      Category: "top",
      slug: "printed-top",
      id: "printedtop",
    },
    {
      src: "/Topsss5ss.jpeg",
      alt: "top",
      title: "Simple Top",
      description: "Keep it effortlessly stylish with this simple top. Designed for comfort and versatility, it&apos;s perfect for everyday wear.",
      price: 100,
      Category: "top",
      slug: "simple-top",
      id: "simple-top",
    },
    {
      src: "/tshirt.jpeg",
      alt: "tshirt",
      title: "T Shirt",
      description: "White T-shirt",
      price: 125,
      Category: "pumpy",
      slug: "pumpy",
      id: "whiteTShirt",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "pumpy",
      slug: "pumpy",
      id: "blackTShirt",
    },
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "Decent Pumpy",
      price: 150,
      Category: "pumpy",
      slug: "pumpy",
      id: "decentPumpy",
    },
    {
      src: "/pntss.jpg",
      alt: "pants",
      title: "Pants",
      description: "Stylish PantsModern and sleek, these pants are crafted for a stylish look. Perfect for casual or smart-casual occasions, they pair seamlessly with any top.",
      price: 200,
      Category: "pants",
      slug: "stylish-pants",
      id: "stylishPants",
    },
    {
      src: "/pants1.jpg",
      alt: "pants",
      title: "Pants",
      description: "These formal pants are tailored to perfection, offering a polished and professional look. Ideal for office wear or formal events.",
      price: 180,
      Category: "formal-pants",
      slug: "formal-pants",
      id: "formalPants",
    },
   
    {
      src: "/jewellerys.jpg",
      alt: "Jewellery",
      title: "Jewewllery",
      description: "Add a touch of elegance to your outfit with this fancy jewellery. Whether for a wedding or a celebration, it&apos;s designed to complement your style.",
      price: 180,
      Category: "Fancy Jewellery",
      slug: "jewellery",
      id: "jewellery1",
    },
    {
      src: "/jewellery1.jpeg",
      alt: "jewellery",
      title: "Stylish jewellery",
      description: "This stylish piece blends contemporary fashion with timeless charm. Perfect for both casual and formal wear, it enhances your overall look.",
      price: 140,
      Category: "Stylish jewellery",
      slug: "jewellery",
      id: "jewellery2",
    },
    {
      src: "/jewelleryss2.jpeg",
      alt: "jewellery",
      title: "Earings",
      description: "Beautifully crafted earrings that combine simplicity and sophistication. A great addition to any outfit, they&apos;re perfect for any occasion",
      price: 160,
      Category: "Earings",
      slug: "jewellery",
      id: "jewellery3",
    },
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "A blend of comfort and elegance, these pumpy shoes are perfect for a day out. Their stylish design adds a trendy touch to your footwear collection.",
      price: 180,
      Category: "Pumpy",
      slug: "pump",
      id: "pumpy1",
    },
    {
      src: "/shoes.jpeg",
      alt: "shoes",
      title: "Shoes",
      description: "Sophisticated and modern, these shoes are designed for a chic look. Perfect for parties or casual outings, they guarantee both style and comfort.",
      price: 140,
      Category: "Stylish shoes",
      slug: "shoes",
      id: "shoes2",
    },
    {
      src: "/shoess.jpg",
      alt: "shoes",
      title: "Jogers Shoes",
      description: "Lightweight and trendy, these joggers are ideal for everyday wear. Their sporty design ensures maximum comfort while keeping you in style.",
      price: 160,
      Category: "jogers",
      slug: "jogers",
      id: "jogers3",
    }

  ];
  
  
  export const PantProduct = [
    {
      src: "/pntss.jpg",
      alt: "pants",
      title: "Pants",
      description: "Stylish PantsModern and sleek, these pants are crafted for a stylish look. Perfect for casual or smart-casual occasions, they pair seamlessly with any top.",
      price: 200,
      Category: "pants",
      slug: "stylish-pants",
      id: "stylishPants",
    },
    {
      src: "/pants1.jpg",
      alt: "pants",
      title: "Pants",
      description: "These formal pants are tailored to perfection, offering a polished and professional look. Ideal for office wear or formal events.",
      price: 180,
      Category: "formal-pants",
      slug: "formal-pants",
      id: "formalPants",
    },
   
  
  ];

  export const topProduct = [
    {
      src: "/topyyii.jpg",
      alt: "top",
      title: "Red top",
      description: "A stylish red top, perfect for casual outings. Its vibrant color adds a bold statement to your wardrobe.",
      price: 125,
      Category: "Red-top",
      slug: "tops",
      id: "top1",
    },
    {
      src: "/topss1.jpg",
      alt: "tshirt",
      title: "Black top",
      description: "A classic black top that offers simplicity and versatility. Ideal for pairing with any outfit, it&apos;s a must-have for every season",
      price: 100,
      Category: "black-top",
      slug: "black-top",
      id: "blackTop",
    },
    {
      src: "/Top2.jpeg",
      alt: "top",
      title: "White Top",
      description: "Elevate your look with this elegant white top. Its minimalistic design makes it a great choice for both casual and semi-formal occasions.",
      price: 125,
      Category: "White Top",
      slug: "white-top",
      id: "whiteTop",
    },
    {
      src: "/top3.jpg",
      alt: "top",
      title: "Fancy Top",
      description: "This fancy top combines modern style with a touch of glam. Perfect for parties or special events, it&apos;s designed to make a statement.",
      price:220,
      Category: "top",
      slug: "fancy-top",
      id: "fancytop",
    },
    {src: "/Topss4.jpg",
      alt: "top",
      title: "Printed top",
      description: "A floral-printed top that exudes charm and vibrancy. Its playful design is great for summer outings and adds a cheerful vibe to your style.",
      price: 100,
      Category: "top",
      slug: "printed-top",
      id: "printedtop",
    },
    {
      src: "/Topsss5ss.jpeg",
      alt: "top",
      title: "Simple Top",
      description: "Keep it effortlessly stylish with this simple top. Designed for comfort and versatility, it&apos;s perfect for everyday wear.",
      price: 100,
      Category: "top",
      slug: "simple-top",
      id: "simple-top",
    },
  ];
  export const jewelleryProduct = [
    {
      src: "/jewellerys.jpg",
      alt: "Jewellery",
      title: "Jewewllery",
      description: "Add a touch of elegance to your outfit with this fancy jewellery. Whether for a wedding or a celebration, it&apos;s designed to complement your style.",
      price: 180,
      Category: "Fancy Jewellery",
      slug: "jewellery",
      id: "jewellery1",
    },
    {
      src: "/jewellery1.jpeg",
      alt: "jewellery",
      title: "Stylish jewellery",
      description: "This stylish piece blends contemporary fashion with timeless charm. Perfect for both casual and formal wear, it enhances your overall look.",
      price: 140,
      Category: "Stylish jewellery",
      slug: "jewellery",
      id: "jewellery2",
    },
    {
      src: "/jewelleryss2.jpeg",
      alt: "jewellery",
      title: "Earings",
      description: "Beautifully crafted earrings that combine simplicity and sophistication. A great addition to any outfit, they&apos;re perfect for any occasion",
      price: 160,
      Category: "Earings",
      slug: "jewellery",
      id: "jewellery3",
    },
  ]
  
  export const shoesProduct = [
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "A blend of comfort and elegance, these pumpy shoes are perfect for a day out. Their stylish design adds a trendy touch to your footwear collection.",
      price: 180,
      Category: "Pumpy",
      slug: "pump",
      id: "pumpy1",
    },
    {
      src: "/shoes.jpeg",
      alt: "shoes",
      title: "Shoes",
      description: "Sophisticated and modern, these shoes are designed for a chic look. Perfect for parties or casual outings, they guarantee both style and comfort.",
      price: 140,
      Category: "Stylish shoes",
      slug: "shoes",
      id: "shoes2",
    },
    {
      src: "/shoess.jpg",
      alt: "shoes",
      title: "Jogers shoes",
      description: "Lightweight and trendy, these joggers are ideal for everyday wear. Their sporty design ensures maximum comfort while keeping you in style.",
      price: 160,
      Category: "jogers",
      slug: "jogers",
      id: "jogers3",
    }
  ]
 