
export const products = [
    {
      src: "/top.jpg",
      alt: "top",
      title: "Red top",
      description: "A stylish red top, perfect for casual outings. Its vibrant color adds a bold statement to your wardrobe.",
      price: 125,
      Category: "Red-top",
      slug: "tops",
      id: "top1",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "black-tshirt",
      slug: "black-shirt",
      id: "blackTShirt",
    },
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "Decent Pumpy",
      price: 150,
      Category: "pumpy",
      slug: "pumpy",
      id: "decentPumpy",
    },
    {
      src: "/tshirt.jpeg",
      alt: "tshirt",
      title: "T Shirt",
      description: "White T-shirt",
      price: 125,
      Category: "pumpy",
      slug: "pumpy",
      id: "whiteTShirt",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "pumpy",
      slug: "pumpy",
      id: "blackTShirt",
    },
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "Decent Pumpy",
      price: 150,
      Category: "pumpy",
      slug: "pumpy",
      id: "decentPumpy",
    },
    {
      src: "/tshirt.jpeg",
      alt: "tshirt",
      title: "T Shirt",
      description: "White T-shirt",
      price: 125,
      Category: "pumpy",
      slug: "pumpy",
      id: "whiteTShirt",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "pumpy",
      slug: "pumpy",
      id: "blackTShirt",
    },
    {
      src: "/pumpy.jpg",
      alt: "pumpy",
      title: "Pumpy",
      description: "Decent Pumpy",
      price: 150,
      Category: "pumpy",
      slug: "pumpy",
      id: "decentPumpy",
    },
    {
      src: "/pants.webp",
      alt: "pants",
      title: "Pants",
      description: "Stylish Pants",
      price: 200,
      Category: "pants",
      slug: "stylish-pants",
      id: "stylishPants",
    },
    {
      src: "/formal-pants.webp",
      alt: "pants",
      title: "Pants",
      description: "Formal Pants",
      price: 180,
      Category: "formal-pants",
      slug: "formal-pants",
      id: "formalPants",
    },
  ];
  
  
  export const PantProduct = [
    {
      src: "/pants.webp",
      alt: "pants",
      title: "Pants",
      description: "Stylish Pants",
      price: 200,
      Category: "pants",
      slug: "stylish-pants",
      id: "stylishPants",
    },
    {
      src: "/formal-pants.webp",
      alt: "pants",
      title: "Pants",
      description: "Formal Pants",
      price: 180,
      Category: "formal-pants",
      slug: "formal-pants",
      id: "formalPants",
    },
  ];

  export const topProducts = [
    {
      src: "/top.jpg",
      alt: "tops",
      title: "Tops",
      description: "Fancy Tops",
      price: 125,
      Category: "tops",
      slug: "tops",
      id: "top1",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "black-tshirt",
      slug: "black-shirt",
      id: "blackTShirt",
    },
    {
      src: "/tshirt.jpeg",
      alt: "tshirt",
      title: "T Shirt",
      description: "White T-shirt",
      price: 125,
      Category: "pumpy",
      slug: "pumpy",
      id: "whiteTShirt",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "pumpy",
      slug: "pumpy",
      id: "blackTShirt",
    },
    {
      src: "/tshirt.jpeg",
      alt: "tshirt",
      title: "T Shirt",
      description: "White T-shirt",
      price: 125,
      Category: "pumpy",
      slug: "pumpy",
      id: "whiteTShirt",
    },
    {
      src: "/blacktshirt.jpg",
      alt: "tshirt",
      title: "T Shirt",
      description: "Black T-shirt",
      price: 100,
      Category: "pumpy",
      slug: "pumpy",
      id: "blackTShirt",
    },
  ];
  